echo "                                       "
echo "                            :.....~           "
echo "                      ..I77777777777777..     "
echo "                   :.7777777777777777777$I.$  "
echo "                 .,I777777777777777777777777,,"
echo "               +~I77777777777777777777777$$$7$.?"
echo "              .7777777777777777777777777$$$$$$$$."
echo "             .?777777777777....,....$$$$$$$$$$$$Z."
echo "            .77777777777 Z           I.$7$$$$$$$$7."
echo "           .7777777777.                 .$$$$$$$$$$."
echo "          .7777777777=                   $?$$$$$$$$$."
echo "         N$77777777.8                     NI$$$$$$$$+"
echo "         .77777777$                        +ZZ$$$$$$$."
echo "         .7777777$.         .Z$$$$.         .$$$$$$$$."
echo "         Z7777777\$7        ,$$$$$$$.        $$$$$$$$$O"
echo "         \$77777$$$        .$$$$$$$$$.        Z$$$$$ZZZ"
echo "         \$77$$$$$$        .$$$$$$$$$.        7Z$ZZZZZZD"
echo "         $$$$$$\$7$8        +$$$$$$$$.        7$ZZZZZZZD           "
echo "         .$$$$$$$$.        N.$Z$$$$$.        7ZZZZZZZZD           "
echo "         .$$$$$$$$=           7,,,,,.        7ZZZZZZZZD           "
echo "         O$$$$$$$$Z.                         7ZZZZZZZZD           "
echo "          .$$$$$$$$$.                        $ZZZZZZZZD           "
echo "           .$$$$$$$$$Z,                      OZZZZZZZZ            "
echo "            ~$$$$$$$$$$Z,                   .ZZZZZZZZ7            "
echo "             ~$$$$$$$$$$ZZ=. O            .:ZZZZZZZZZ.            "
echo "              .Z$$$$$$$$ZZ$Z$ZZZZZZZZZZZZZZZZZZZZZZZ~D            "
echo "                Z$$$$$ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZO:             "
echo "                 .O$ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ=              "
echo "                   ..Z$ZZZZZZZZZZZZZZZZZZZZZZZZZO.                "
echo "                      ..Z$ZZZZZZZZZZZZZZZZZZZZI."
echo "                          N.................I"
echo "                                       "

